"""added voiceban_role column to guilds table

Revision ID: 03a23b19e664
Revises: ffc5a935e7e9
Create Date: 2021-09-26 20:02:57.787673

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03a23b19e664'
down_revision = 'ffc5a935e7e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('guilds', sa.Column('voiceban_role', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('guilds', 'voiceban_role')
    # ### end Alembic commands ###
