"""added muted_role column to guilds table

Revision ID: 0439e4f42a67
Revises: 97d93ee5aec8
Create Date: 2021-09-24 20:43:43.484895

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0439e4f42a67'
down_revision = '97d93ee5aec8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('guilds', sa.Column('muted_role', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('guilds', 'muted_role')
    # ### end Alembic commands ###
