"""added infractions and reminders tables

Revision ID: 213b2c97361f
Revises: 3c650ea4107e
Create Date: 2021-09-19 13:52:58.213836

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '213b2c97361f'
down_revision = '3c650ea4107e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('infractions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('actor', sa.String(), nullable=True),
    sa.Column('hidden', sa.Boolean(), nullable=True),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('user', sa.String(), nullable=True),
    sa.Column('guild', sa.String(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('permanent', sa.Boolean(), nullable=True),
    sa.Column('inserted_at', sa.DateTime(), nullable=True),
    sa.Column('expiry', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reminders',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('author', sa.String(), nullable=True),
    sa.Column('channel_id', sa.String(), nullable=True),
    sa.Column('jump_url', sa.String(), nullable=True),
    sa.Column('content', sa.String(), nullable=True),
    sa.Column('expiration', sa.DateTime(), nullable=True),
    sa.Column('mentions', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reminders')
    op.drop_table('infractions')
    # ### end Alembic commands ###
