"""perhaps ints weren't the answer

Revision ID: 68e4dc1b14c4
Revises: 9ee00410f0a0
Create Date: 2021-09-05 17:21:08.274441

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68e4dc1b14c4'
down_revision = '9ee00410f0a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
