"""added inserted_at column

Revision ID: 6a517d52c199
Revises: d7f97f57b141
Create Date: 2022-05-10 23:04:05.802681

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a517d52c199'
down_revision = 'd7f97f57b141'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message_logs', sa.Column('inserted_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('message_logs', 'inserted_at')
    # ### end Alembic commands ###
