"""added message log table

Revision ID: d7f97f57b141
Revises: 133cb8a9d265
Create Date: 2022-05-10 22:59:10.816727

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd7f97f57b141'
down_revision = '133cb8a9d265'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('message_logs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('actor', sa.String(), nullable=True),
    sa.Column('guild', sa.String(), nullable=True),
    sa.Column('messages', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('message_logs')
    # ### end Alembic commands ###
