"""made server_logs_channel column nullable

Revision ID: ffc5a935e7e9
Revises: 0439e4f42a67
Create Date: 2021-09-24 21:16:44.968014

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ffc5a935e7e9'
down_revision = '0439e4f42a67'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
